### ISSUE TITLE
Consider other base32 implementations

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/rs-stellar-strkey#10]
Consider other base32 implementations

See todo comments:
- https://github.com/stellar/rs-stellar-strkey/blob/e9bca80eb2dff582e49b2db452ece083dc8ed5ff/src/strkey.rs#L113-L115

**Comment by overcat** [comment]
Maybe [data-encoding](https://crates.io/crates/data-encoding) is a good option? All test cases can be passed.
