### ISSUE TITLE
Consider renaming the PublicKey type with a Strkey prefix

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/rs-stellar-strkey#22]
@tomerweller Since the strkey package's PublicKey will always collide with the xdr packages PublicKey, I wonder if we should just name it `StrkeyPublicKey` in the strkey crate 🤔. It's more likely to result in us naming it the same thing everywhere. Wdyt?

_Originally posted by @leighmcculloch in https://github.com/stellar/rs-stellar-contract-sdk/pull/68#discussion_r862297457_

**Comment by tomerweller** [comment]
between this and #23 we're getting some extremely verbose names
`PublicKey` -> `StrkeyPublicKeyEd25519`. Is it possible to instead alias these when using consuming them?

**Comment by tomerweller** [comment]
(TBH, after writing it down `StrkeyPublicKeyEd25519` doesn't sound that bad)

**Comment by leighmcculloch** [comment]
I think this change you made improves readability though. It's actually better alongside the xdr.

This makes me wonder. There will be two primary places typically you use a strkey:

1. With the xdr to set accounts and signers in txs.

2. For signing or verifying in the case of public and private keys.

Ideally people don't use the strkey package directly too much. But I also don't think we should make the xdr package depend on strkey. We did the former in the Go XDR and it has been a pain. 

I think we need to think about what our strategy is going to be for glue like stuff between these and other packages. Maybe we have a `rs-stellar` package that reexports all the other crates and provides only some glue between them. So we'd implement From<&str> for the xdr AccpuntId type in the glue package, and it'd use the strkey package.

If we're going to do something like that it begs the question should all these crate be just one crate? I don't think so, but maybe I'm wrong. I'm typically a fan of monorepos so I'm weary that I could be biased towards that even if it isn't necessary.

**Comment by leighmcculloch** [comment]
The good news is we can always add glue later, this isn't a pressing issue, and there's a ton of other things we should focus on. And since consolidation is always easier than separation, I think we are doing the right thing starting out with many small components.
