### ISSUE TITLE
Add a function for checking if strkey is compatible with Soroban

### ISSUE THREAD

**Issue by dmkozh** [stellar/rs-stellar-strkey#63]
### What problem does your feature solve?

A generic way for clients to verify that a given strkey is not just valid for generic Stellar transactions, but is also valid for Soroban. Soroban host could also use that function to ensure consistency in case if we ever need to reduce the address space.

### What would you like to see?

A function that for a given `Strkey` object returns whether it's also a valid Soroban address (i.e. G-account or contract currently).

### What alternatives are there?

Implement rules manually on the client side - that doesn't guarantee consistency in case if Soroban is updated.

### Discussion

Related discussion offline:
- https://stellarfoundation.slack.com/archives/C04545F3S59/p1723152981541409

**Comment by leighmcculloch** [comment]
Support in Soroban is somewhat broad concept. It might be more useful to make the address concept more specific and to add a type that parses strkeys that are addresses, so it'd support G and C addresses.

Would that help with the situation this is for? Could you tell more about hte situation?

**Comment by dmkozh** [comment]
> It might be more useful to make the address concept more specific and to add a type that parses strkeys that are addresses,

That's an option as well, my initial suggestion requires minimal amount of work, but probably using a separate type would be more clear.

> Would that help with the situation this is for? Could you tell more about hte situation?

Currently there is no good way to tell if a strkey is a valid Soroban address. While one could manually check that it starts with G/C today, there is no guarantee that we won't support new address types in the future. Which is why it is useful to have the validation in strkey library, given that it's already necessary to just parse the strkey. The use case that motivated this issue is validation performed by the bridges - they need to sanity check the strkey in the cross-chain message that comes from a different chain.

**Comment by leighmcculloch** [comment]
> there is no guarantee that we won't support new address types in the gvdhggughiojrepogufeioghtriusgh trioukhjtilrjht5u4iowtu45iwotu54oiw;v













a






























































































































































































khfgcjklbdrgfjxvblnk, fhmxb

**Comment by leighmcculloch** [comment]
Ah, so if someone wants to figure out if a strkey is a valid Soroban Address, then they can already do that by using the `ScAddress` type in the stellar-xdr lib.

```rust
ScAddress::from_str("G/C....")
```

The type implements the stdlib `FromStr` trait, which returns either an `ScAddress`, or an error.

**Comment by dmkozh** [comment]
Cool, I wasn't aware of that function. Yes, it seems like a more appropriate solution here.
